### ISSUE TITLE
Generate PDF directly

### ISSUE THREAD

**Issue by kpolkovnikov** [boldreports/report-viewer-with-syncfusion-blazor-components#4]
Hi. It's possible to generate PDF directly from RDL report without viewing?

**Comment by karthickthangasamy** [comment]
Hi @kpolkovnikov ,

Yes, we can export directly using our [Report Writer](https://www.boldreports.com/embedded-reporting/report-writer) component.

https://help.boldreports.com/embedded-reporting/aspnet-mvc-reporting/report-writer/export-ssrs-rdl-report/

Thanks,
Karthick T

**Comment by kpolkovnikov** [comment]
Thanks,

**Comment by kpolkovnikov** [comment]
Is it possible to pass the parameters from Blazor Page to BoldReportWriterController, except through the route?
